# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-05 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('in_use', models.BooleanField(default=False, verbose_name='Em uso')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Product', verbose_name='Produto')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
    ]
