# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='in_use',
            field=models.BooleanField(default=True, verbose_name='Em uso'),
        ),
    ]
