# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-10 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180531_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='plots',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
    ]
