# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180610_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='pay_sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='products.Pay'),
        ),
        migrations.AddField(
            model_name='plot',
            name='plot_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='products.Plot'),
        ),
        migrations.AddField(
            model_name='productsale',
            name='product_sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Sale'),
        ),
    ]
