# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180610_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='pay_sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='products.Sale'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product_sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.Sale'),
        ),
    ]
