# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-10 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180610_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='products.Pay'),
        ),
    ]
