# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180610_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
