# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['created', 'status'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AddField(
            model_name='product',
            name='enable_deduction',
            field=models.BooleanField(default=True, verbose_name='Habilitar desconto'),
        ),
    ]
