# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-31 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20181219_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='enable_deduction',
            field=models.BooleanField(default=False, verbose_name='Habilitar desconto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='enable_deduction',
            field=models.BooleanField(default=False, verbose_name='Habilitar desconto'),
        ),
    ]
