# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-07 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190331_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_trade', to='products.Price', verbose_name='Preço')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_trade', to='products.Product', verbose_name='Produto')),
                ('sale', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_trade', to='products.Sale')),
            ],
        ),
        migrations.AlterField(
            model_name='productsale',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_sale', to='products.Price', verbose_name='Preço'),
        ),
    ]
