# Generated by Django 2.2.1 on 2019-06-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20190514_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plot',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id', 'code'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productsale',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='producttrade',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay_sale',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='products.Sale'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='products.Pay'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_sale', to='products.Price', verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sale', to='products.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product_sale',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.Sale'),
        ),
        migrations.AlterField(
            model_name='producttrade',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_trade', to='products.Price', verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='producttrade',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_trade', to='products.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='producttrade',
            name='sale',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_trade', to='products.Sale'),
        ),
    ]
