# Generated by Django 2.2.1 on 2019-06-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20190608_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='whole_sale_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Valor Atacado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='whole_sale',
            field=models.BooleanField(default=False, verbose_name='Atacado?'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor Varejo'),
        ),
    ]
