# Generated by Django 2.2.1 on 2019-09-07 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0024_auto_20190623_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('reason', models.CharField(choices=[('TF', 'Transferência'), ('TR', 'Troca'), ('V', 'Venda'), ('C', 'Correção')], max_length=2, verbose_name='Motivo')),
                ('type', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=2, verbose_name='Tipo')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product', verbose_name='Produto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='Loja')),
            ],
            options={
                'ordering': ['id', 'date'],
            },
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('product_operation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_operation', to='products.ProductOperation')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_stock_operation', to='products.Stock')),
            ],
            options={
                'verbose_name': 'Operação de Estoque',
                'verbose_name_plural': 'Operações de Estoque',
                'ordering': ['id', 'created'],
            },
        ),
    ]
