# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='employees/', verbose_name='Foto')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=16, verbose_name='CPF')),
                ('rg', models.CharField(max_length=16, verbose_name='RG')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Salário')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Career', verbose_name='Função')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
    ]
