# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('behavior_type', models.CharField(choices=[('A', 'Advertência'), ('P', 'Prêmio')], max_length=2, verbose_name='Tipo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='Funcionário')),
            ],
            options={
                'ordering': ['date', 'behavior_type'],
            },
        ),
    ]
