# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-04 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_behaviorsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'Janeiro'), ('FEV', 'Feveireiro'), ('MAR', 'Março'), ('ABR', 'ABRIL'), ('MAI', 'Maio'), ('JUN', 'Junho'), ('JUL', 'Julho'), ('AGO', 'Agosto'), ('SET', 'Setembro'), ('OUT', 'Outubro'), ('NOV', 'Novembro'), ('DEZ', 'Dezembro')], max_length=3, verbose_name='Mês')),
                ('year', models.CharField(max_length=4, verbose_name='Ano')),
                ('shift_start', models.TimeField(default='08:30', verbose_name='Inicio do turno')),
                ('shift_end', models.TimeField(default='18:00', verbose_name='Fim do turno')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee')),
            ],
            options={
                'ordering': ['month', 'year'],
            },
        ),
    ]
