# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-04 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_workschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_start', models.TimeField(default='08:30', verbose_name='Inicio do turno da manhã')),
                ('m_end', models.TimeField(default='12:30', verbose_name='Fim do turno da manhã')),
                ('a_start', models.TimeField(default='13:30', verbose_name='Inicio do turno da tarde')),
                ('a_end', models.TimeField(default='18:00', verbose_name='Fim do turno da tarde')),
                ('allowance', models.CharField(blank=True, choices=[('FO', 'Folga'), ('AT', 'Atestado'), ('DE', 'Declaração'), ('DR', 'Descanso Remunerado')], max_length=2, null=True, verbose_name='Abonos')),
                ('reduced_day', models.BooleanField(default=False, verbose_name='Jornada reduzida')),
            ],
            options={
                'ordering': ['m_start', 'a_end'],
                'verbose_name': 'Horário trabalhado',
                'verbose_name_plural': 'Horários trabalhados',
            },
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['month', 'year'], 'verbose_name': 'Controle de Ponto', 'verbose_name_plural': 'Controles de pontos'},
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='work_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='users.WorkSchedule', verbose_name='Ponto'),
        ),
    ]
