# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181004_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='date',
            field=models.DateField(default='2018-01-01', verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='e_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim da hora extra'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='e_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio da hora extra'),
        ),
    ]
