# Generated by Django 2.2.1 on 2019-05-12 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181020_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorsheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Career', verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='work_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_shifts', to='users.WorkSchedule', verbose_name='Ponto'),
        ),
    ]
