# Generated by Django 2.2.1 on 2019-06-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190512_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorsheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Career', verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='work_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='users.WorkSchedule', verbose_name='Ponto'),
        ),
    ]
