# Generated by Django 2.2.1 on 2019-06-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190608_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name', 'code'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit',
            field=models.CharField(max_length=20, null=True, verbose_name='Carteira de Trabalho'),
        ),
        migrations.AlterField(
            model_name='behaviorsheet',
            name='behavior_type',
            field=models.CharField(choices=[('A', 'Advertência'), ('AT', 'Atestado'), ('P', 'Prêmio'), ('F', 'Falta')], max_length=2, verbose_name='Tipo'),
        ),
    ]
