# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=16, verbose_name='CPF')),
                ('rg', models.CharField(max_length=16, verbose_name='RG')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('cellphone', models.TextField(blank=True, null=True, verbose_name='Celular')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Telefone')),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='users.Employee',
                        verbose_name='Vendedora'
                    )
                ),
            ],
            options={
                'ordering': ['name', 'cpf'],
            },
        ),
    ]
