# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-09 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cep',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CEP'),
        ),
    ]
