# Generated by Django 2.2.1 on 2019-06-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180110_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Employee', verbose_name='Vendedora'),
        ),
    ]
